\import Paths
\import interface
\import lang
\import uPred
\import cmra
\import weakestpre
\import lib.heap
\import lib.gmap_cmra
\import lib.excl_cmra

-- =================================================================================
-- Hoare triples
-- =================================================================================

\func ht
  {cnt : Countable Loc}
  (P   : ProperUPred (HeapCMRA Loc cnt Value))
  (e   : Expr)
  (Phi : Value -> ProperUPred (HeapCMRA Loc cnt Value))
  : ProperUPred (HeapCMRA Loc cnt Value)
  => mkProperPersistently (mkProperWand P (wp e Phi))


-- =================================================================================
-- Hoare-triple rules
-- =================================================================================


\lemma ht_conseq
  {cnt : Countable Loc}
  (P P' : ProperUPred (HeapCMRA Loc cnt Value))
  (e    : Expr)
  (Phi Phi' : Value -> ProperUPred (HeapCMRA Loc cnt Value))
  (hP   : properUPred_ent P' P)
  (hPhi : \Pi (v : Value) -> properUPred_ent (Phi v) (Phi' v))
  : properUPred_ent (ht P e Phi) (ht P' e Phi')
  =>
    \let M => HeapCMRA Loc cnt Value
    \in \lam n a hv h_pers =>
        \lam m m_le_n b unit_incl_b =>
            \lam k k_le_m a' hv_b_a' hP'_a' =>
                \let
                  | hv_a' : M.validN k a' =>
                    M.cmra_validN_op_l k a' b
                        (transport (\lam w => M.validN k w) (M.cmra_comm b a') hv_b_a')
                  | hP_a' : P.upred_holds k a' => hP k a' hv_a' hP'_a'
                  | hwand : (mkProperWand P (wp e Phi)).upred_holds m b =>
                    h_pers m m_le_n b unit_incl_b
                  | h_wp_b_a' : (wp e Phi).upred_holds k (M.op b a') =>
                    hwand k k_le_m a' hv_b_a' hP_a'
                \in wp_post_mono e Phi Phi' hPhi k (M.op b a') hv_b_a' h_wp_b_a'